name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # ensure ALL LFS files are downloaded locally
      - name: Pull LFS files
        run: |
          git lfs install
          git lfs fetch --all
          git lfs checkout

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Manually Extract the backend folder
          mkdir -p ../deploy_space
          cp -r backend/* ../deploy_space/
          
          # 2. Enter the folder and initialize it as a new repo
          cd ../deploy_space
          git init
          git checkout -b main
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Direct deploy: Full files (No pointers)"
          
          # 3. Add HF Remote
          git remote add space-remote https://kushagramkhare:${HF_TOKEN}@huggingface.co/spaces/kushagramkhare/institute_RAG_assistant
          
          # 4. CRUCIAL: Force-Push the REAL files
          git lfs install
          # We push the local 'main' branch to the remote 'main' branch
          git push space-remote main --force